"""empty message

Revision ID: 036f54c7b5d0
Revises: 4203fc1b208b
Create Date: 2021-01-03 14:43:24.487641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '036f54c7b5d0'
down_revision = '4203fc1b208b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'future__price__list', 'booking', ['booking_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'past__price__list', 'booking', ['booking_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'past__price__list', type_='foreignkey')
    op.drop_constraint(None, 'future__price__list', type_='foreignkey')
    # ### end Alembic commands ###
