"""empty message

Revision ID: 049442e7b29d
Revises: f8e272ff1959
Create Date: 2021-03-28 16:00:09.160327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '049442e7b29d'
down_revision = 'f8e272ff1959'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cancellation__breakpoint', sa.Column('check_in', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cancellation__breakpoint', 'check_in')
    # ### end Alembic commands ###
