"""empty message

Revision ID: 06fa25c57cc6
Revises: 276dd3935b3e
Create Date: 2021-03-26 16:43:11.195652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06fa25c57cc6'
down_revision = '276dd3935b3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment__breakpoint', sa.Column('due_on_receipt', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment__breakpoint', 'due_on_receipt')
    # ### end Alembic commands ###
