"""added min_age col to price_list_settings table

Revision ID: 086ea46b6e0f
Revises: 0f4645f9b2c0
Create Date: 2021-04-25 11:25:20.094460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '086ea46b6e0f'
down_revision = '0f4645f9b2c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price__list__settings', sa.Column('min_age', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('price__list__settings', 'min_age')
    # ### end Alembic commands ###
