"""empty message

Revision ID: 09aa510c609a
Revises: f192a22175c8
Create Date: 2020-12-13 12:51:58.681248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09aa510c609a'
down_revision = 'f192a22175c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price__list__settings', sa.Column('active_prices_range', sa.Integer(), nullable=True))
    op.add_column('price__list__settings', sa.Column('future_prices_range', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('price__list__settings', 'future_prices_range')
    op.drop_column('price__list__settings', 'active_prices_range')
    # ### end Alembic commands ###
