"""added Billing.last_reminder field

Revision ID: 0c5809777691
Revises: 279a584dd607
Create Date: 2021-05-24 14:52:16.945254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c5809777691'
down_revision = '279a584dd607'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('billing', sa.Column('last_reminder', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('billing', 'last_reminder')
    # ### end Alembic commands ###
