"""changed app.models.Payment to app.models.Billing - to include invoices, payments and credit notes

Revision ID: 0efe594785bf
Revises: 340697e7f37f
Create Date: 2021-03-17 13:56:27.821277

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0efe594785bf'
down_revision = '340697e7f37f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('is_invoice', sa.Boolean(), nullable=True),
    sa.Column('is_payment', sa.Boolean(), nullable=True),
    sa.Column('is_credit', sa.Boolean(), nullable=True),
    sa.Column('is_debit', sa.Boolean(), nullable=True),
    sa.Column('note', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('payment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('booking_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('amount', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('date_received', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], name='payment_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_bin',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('billing')
    # ### end Alembic commands ###
