"""added range_type field to Price_List

Revision ID: 13fba8f4c705
Revises: 57daa8ff7842
Create Date: 2021-05-01 10:39:55.909409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13fba8f4c705'
down_revision = '57daa8ff7842'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price__list', sa.Column('range_type', sa.Enum('PAST', 'ACTIVE', 'FUTURE', name='range_type'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('price__list', 'range_type')
    # ### end Alembic commands ###
