"""empty message

Revision ID: 167d7efb603b
Revises: c17a67ca8134
Create Date: 2021-04-12 16:43:28.513939

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '167d7efb603b'
down_revision = 'c17a67ca8134'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('billing', sa.Column('linked_invoice', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'billing', 'billing', ['linked_invoice'], ['invoice_reference'])
    op.drop_column('billing', 'linked_invoice_reference')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('billing', sa.Column('linked_invoice_reference', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'billing', type_='foreignkey')
    op.drop_column('billing', 'linked_invoice')
    # ### end Alembic commands ###
