"""reduced Price_List.progressive_payents to single relationship

Revision ID: 19a82454ac17
Revises: bcf1ac4a81a9
Create Date: 2021-05-09 12:04:41.776551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19a82454ac17'
down_revision = 'bcf1ac4a81a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('progressive__payment', sa.Column('stay_length_type', sa.Enum('1_WEEK', '2_WEEKS', '3_WEEKS', '4_WEEKS', name='stay_length_type'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('progressive__payment', 'stay_length_type')
    # ### end Alembic commands ###
