"""empty message

Revision ID: 1a3bcda2c84d
Revises: 51116b13d4bf
Create Date: 2021-04-05 13:33:25.564760

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1a3bcda2c84d'
down_revision = '51116b13d4bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('billing', sa.Column('transaction_type', sa.Enum('INVOICE', 'PAYMENT', 'DEBIT_NOTE', 'CREDIT_NOTE', name='transaction_type'), nullable=False))
    op.drop_column('billing', 'type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('billing', sa.Column('type', mysql.ENUM('INVOICE', 'PAYMENT', 'DEBIT_NOTE', 'CREDIT_NOTE', collation='utf8_bin'), nullable=False))
    op.drop_column('billing', 'transaction_type')
    # ### end Alembic commands ###
