"""empty message

Revision ID: 1dc1422416f3
Revises: f731af2d82b1
Create Date: 2020-12-17 18:51:29.955040

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1dc1422416f3'
down_revision = 'f731af2d82b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price__list__settings', sa.Column('max_segment_length', sa.Integer(), nullable=True))
    op.drop_column('price__list__settings', 'max_segment_lengh')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price__list__settings', sa.Column('max_segment_lengh', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('price__list__settings', 'max_segment_length')
    # ### end Alembic commands ###
