"""empty message

Revision ID: 1f8944f37972
Revises: 9aaec0f42ca3
Create Date: 2021-06-14 19:51:46.292263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f8944f37972'
down_revision = '9aaec0f42ca3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('credit_note_reference', table_name='delete__billing')
    op.drop_index('debit_note_reference', table_name='delete__billing')
    op.drop_index('invoice_reference', table_name='delete__billing')
    op.drop_index('linked_invoice_id', table_name='delete__billing')
    op.drop_index('payment_reference', table_name='delete__billing')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('payment_reference', 'delete__billing', ['payment_reference'], unique=True)
    op.create_index('linked_invoice_id', 'delete__billing', ['linked_invoice_id'], unique=True)
    op.create_index('invoice_reference', 'delete__billing', ['invoice_reference'], unique=True)
    op.create_index('debit_note_reference', 'delete__billing', ['debit_note_reference'], unique=True)
    op.create_index('credit_note_reference', 'delete__billing', ['credit_note_reference'], unique=True)
    # ### end Alembic commands ###
