"""empty message

Revision ID: 23d909e3d3c6
Revises: b13f8c6a5b07
Create Date: 2020-12-12 12:18:26.684417

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '23d909e3d3c6'
down_revision = 'b13f8c6a5b07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price__list', sa.Column('price_2_weeks', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('price__list', sa.Column('price_3_weeks', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('price__list', sa.Column('price_4_weeks', sa.Numeric(precision=10, scale=2), nullable=True))
    op.drop_column('price__list', 'price_2_week')
    op.drop_column('price__list', 'price_4_week')
    op.drop_column('price__list', 'price_3_week')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price__list', sa.Column('price_3_week', mysql.DECIMAL(precision=10, scale=2), nullable=True))
    op.add_column('price__list', sa.Column('price_4_week', mysql.DECIMAL(precision=10, scale=2), nullable=True))
    op.add_column('price__list', sa.Column('price_2_week', mysql.DECIMAL(precision=10, scale=2), nullable=True))
    op.drop_column('price__list', 'price_4_weeks')
    op.drop_column('price__list', 'price_3_weeks')
    op.drop_column('price__list', 'price_2_weeks')
    # ### end Alembic commands ###
