"""empty message

Revision ID: 276dd3935b3e
Revises: d21d6dec7b63
Create Date: 2021-03-25 13:50:01.222186

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '276dd3935b3e'
down_revision = 'd21d6dec7b63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('billing', sa.Column('credit_note_reference', sa.Integer(), nullable=True))
    op.add_column('billing', sa.Column('debit_note_reference', sa.Integer(), nullable=True))
    op.add_column('billing', sa.Column('invoice_due_date', sa.Date(), nullable=True))
    op.add_column('billing', sa.Column('invoice_reference', sa.Integer(), nullable=True))
    op.add_column('billing', sa.Column('payment_reference', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'billing', ['credit_note_reference'])
    op.create_unique_constraint(None, 'billing', ['debit_note_reference'])
    op.create_unique_constraint(None, 'billing', ['payment_reference'])
    op.create_unique_constraint(None, 'billing', ['invoice_reference'])
    op.add_column('cancellation__breakpoint', sa.Column('cancel_by', sa.Integer(), nullable=True))
    op.drop_column('cancellation__breakpoint', 'is_percentage')
    op.drop_column('cancellation__breakpoint', 'is_absolute')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cancellation__breakpoint', sa.Column('is_absolute', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('cancellation__breakpoint', sa.Column('is_percentage', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('cancellation__breakpoint', 'cancel_by')
    op.drop_constraint(None, 'billing', type_='unique')
    op.drop_constraint(None, 'billing', type_='unique')
    op.drop_constraint(None, 'billing', type_='unique')
    op.drop_constraint(None, 'billing', type_='unique')
    op.drop_column('billing', 'payment_reference')
    op.drop_column('billing', 'invoice_reference')
    op.drop_column('billing', 'invoice_due_date')
    op.drop_column('billing', 'debit_note_reference')
    op.drop_column('billing', 'credit_note_reference')
    # ### end Alembic commands ###
