"""added Billing_Settings.first_payment_due_after flag

Revision ID: 279a584dd607
Revises: e96232c548c4
Create Date: 2021-05-24 14:33:42.589345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '279a584dd607'
down_revision = 'e96232c548c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('billing_settings', sa.Column('first_payment_due_after', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('billing_settings', 'first_payment_due_after')
    # ### end Alembic commands ###
