"""Booking.multi_week_discount column

Revision ID: 2e16e161d9bc
Revises: 97d9b27f5765
Create Date: 2021-05-17 18:59:46.435933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e16e161d9bc'
down_revision = '97d9b27f5765'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('multi_week_discount', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking', 'multi_week_discount')
    # ### end Alembic commands ###
