"""added Price_List.blocked 

Revision ID: 2eb93092e9eb
Revises: 1f8944f37972
Create Date: 2021-06-19 14:49:53.684486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2eb93092e9eb'
down_revision = '1f8944f37972'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price__list', sa.Column('blocked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('price__list', 'blocked')
    # ### end Alembic commands ###
