"""added Booking.external_note col

Revision ID: 2f4ed0d60ebe
Revises: 51d0bce005b0
Create Date: 2021-07-08 15:02:39.328175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f4ed0d60ebe'
down_revision = '51d0bce005b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('external_note', sa.String(length=30), nullable=True))
    op.add_column('delete__booking', sa.Column('external_note', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('delete__booking', 'external_note')
    op.drop_column('booking', 'external_note')
    # ### end Alembic commands ###
