"""added Payment table and relationship between Payment and Booking. Also added total_du_by date to Booking

Revision ID: 340697e7f37f
Revises: ab200e5bca5c
Create Date: 2021-03-16 16:27:34.870260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '340697e7f37f'
down_revision = 'ab200e5bca5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('date_received', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('booking', sa.Column('total_due_by', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking', 'total_due_by')
    op.drop_table('payment')
    # ### end Alembic commands ###
