"""empty message

Revision ID: 37eadc7e4abc
Revises: b5d2e7331630
Create Date: 2021-07-15 14:39:22.114087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37eadc7e4abc'
down_revision = 'b5d2e7331630'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('billing', sa.Column('invoice_status', sa.Enum('DRAFT', 'ACCEPTED', 'ACTIVE', 'OVERDUE', 'PAID', 'INACTIVE', name='invoice_status'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('billing', 'invoice_status')
    # ### end Alembic commands ###
