"""added Billing_Settings table

Revision ID: 382e254e3efd
Revises: 5176cf22cf75
Create Date: 2021-03-17 20:57:55.344951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '382e254e3efd'
down_revision = '5176cf22cf75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing__settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('billing__settings')
    # ### end Alembic commands ###
