"""empty message

Revision ID: 3fdc3ebbf907
Revises: 2e16e161d9bc
Create Date: 2021-05-22 09:52:34.811756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fdc3ebbf907'
down_revision = '2e16e161d9bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('status', sa.Enum('AWAITING_CONFIRMATION', 'ACCEPTED', 'REJECTED', 'ACTIVE', 'INACTIVE', name='status'), nullable=True))
    op.drop_column('booking', 'total_due_by')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('total_due_by', sa.DATE(), nullable=True))
    op.drop_column('booking', 'status')
    # ### end Alembic commands ###
