"""empty message

Revision ID: 4203fc1b208b
Revises: 4eb25cf845ef
Create Date: 2021-01-03 14:40:10.262715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4203fc1b208b'
down_revision = '4eb25cf845ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('past__price__list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_2_weeks', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_3_weeks', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_4_weeks', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('start_date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('past__price__list')
    # ### end Alembic commands ###
