"""empty message

Revision ID: 42f19be5b389
Revises: 1dc1422416f3
Create Date: 2020-12-24 10:46:41.397350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42f19be5b389'
down_revision = '1dc1422416f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price__list__settings', sa.Column('max_dogs', sa.Integer(), nullable=True))
    op.add_column('price__list__settings', sa.Column('max_guests', sa.Integer(), nullable=True))
    op.add_column('price__list__settings', sa.Column('max_infants', sa.Integer(), nullable=True))
    op.add_column('price__list__settings', sa.Column('price_per_dog', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('price__list__settings', 'price_per_dog')
    op.drop_column('price__list__settings', 'max_infants')
    op.drop_column('price__list__settings', 'max_guests')
    op.drop_column('price__list__settings', 'max_dogs')
    # ### end Alembic commands ###
