"""empty message

Revision ID: 4cea9aa0790a
Revises: 049442e7b29d
Create Date: 2021-03-28 16:03:15.569787

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4cea9aa0790a'
down_revision = '049442e7b29d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cancellation__breakpoint', 'check_in')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cancellation__breakpoint', sa.Column('check_in', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
