"""added Delete_Booking.booking_type col

Revision ID: 4d611d1ccde6
Revises: 89fa0a6d3309
Create Date: 2021-07-07 17:43:33.142594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d611d1ccde6'
down_revision = '89fa0a6d3309'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delete__booking', sa.Column('booking_type', sa.Enum('standard', 'owner', 'external'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('delete__booking', 'booking_type')
    # ### end Alembic commands ###
