"""empty message

Revision ID: 4eb25cf845ef
Revises: 6699d5a279a4
Create Date: 2020-12-29 16:38:52.675029

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4eb25cf845ef'
down_revision = '6699d5a279a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('future__price__list', 'booked')
    op.drop_column('price__list', 'booked')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price__list', sa.Column('booked', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('future__price__list', sa.Column('booked', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
