"""empty message

Revision ID: 5074e4c04044
Revises: afc5be7fea2d
Create Date: 2021-05-22 10:16:20.628227

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5074e4c04044'
down_revision = 'afc5be7fea2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('billing', 'invoice_status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('billing', sa.Column('invoice_status', mysql.ENUM('NOT_SENT', 'SENT', 'OVERDUE', 'PAID', collation='utf8_bin'), nullable=True))
    # ### end Alembic commands ###
