"""added enum type column to billing model

Revision ID: 51116b13d4bf
Revises: ed4a0f48eebc
Create Date: 2021-04-05 13:15:55.419004

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '51116b13d4bf'
down_revision = 'ed4a0f48eebc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('billing', sa.Column('type', sa.Enum('INVOICE', 'PAYMENT', 'DEBIT_NOTE', 'CREDIT_NOTE', name='type'), nullable=False))
    op.drop_column('billing', 'is_invoice')
    op.drop_column('billing', 'is_debit')
    op.drop_column('billing', 'is_payment')
    op.drop_column('billing', 'is_credit')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('billing', sa.Column('is_credit', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('billing', sa.Column('is_payment', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('billing', sa.Column('is_debit', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('billing', sa.Column('is_invoice', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('billing', 'type')
    # ### end Alembic commands ###
