"""empty message

Revision ID: 5176cf22cf75
Revises: 0efe594785bf
Create Date: 2021-03-17 14:31:41.859551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5176cf22cf75'
down_revision = '0efe594785bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delete__billing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('is_invoice', sa.Boolean(), nullable=True),
    sa.Column('is_payment', sa.Boolean(), nullable=True),
    sa.Column('is_credit', sa.Boolean(), nullable=True),
    sa.Column('is_debit', sa.Boolean(), nullable=True),
    sa.Column('note', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('delete__billing')
    # ### end Alembic commands ###
