"""empty message

Revision ID: 51d0bce005b0
Revises: 62d6b9f8aca4
Create Date: 2021-07-07 17:53:05.694942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51d0bce005b0'
down_revision = '62d6b9f8aca4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('booking_type', sa.Enum('STANDARD', 'OWNER', 'EXTERNAL', name='booking_type'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking', 'booking_type')
    # ### end Alembic commands ###
