"""empty message

Revision ID: 57daa8ff7842
Revises: 0fb8560fbd80
Create Date: 2021-05-01 10:32:09.614366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57daa8ff7842'
down_revision = '0fb8560fbd80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'delete__billing', ['linked_invoice_id'])
    op.drop_constraint('delete__billing_ibfk_2', 'delete__billing', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('delete__billing_ibfk_2', 'delete__billing', 'billing', ['linked_invoice_id'], ['id'])
    op.drop_constraint(None, 'delete__billing', type_='unique')
    # ### end Alembic commands ###
