"""empty message

Revision ID: 5e5c764f59e5
Revises: 5074e4c04044
Create Date: 2021-05-22 10:16:41.587048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e5c764f59e5'
down_revision = '5074e4c04044'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('billing', sa.Column('invoice_status', sa.Enum('DRAFT', 'ACTIVE', 'OVERDUE', 'PAID', 'INACTIVE', name='invoice_status'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('billing', 'invoice_status')
    # ### end Alembic commands ###
