"""added Billing.percentage_due field

Revision ID: 5ff81f5918f2
Revises: 0c5809777691
Create Date: 2021-05-24 14:55:32.359565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ff81f5918f2'
down_revision = '0c5809777691'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('billing', sa.Column('percentage_due', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('billing', 'percentage_due')
    # ### end Alembic commands ###
