"""empty message

Revision ID: 62d6b9f8aca4
Revises: 4d611d1ccde6
Create Date: 2021-07-07 17:52:56.750661

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '62d6b9f8aca4'
down_revision = '4d611d1ccde6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking', 'booking_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('booking_type', mysql.ENUM('standard', 'owner', 'external', collation='utf8_bin'), nullable=False))
    # ### end Alembic commands ###
