"""added is_future, is_active booleans to Price_List model. added Past_Price_List model for storing old prices

Revision ID: 65ad66588403
Revises: 8979d20983d0
Create Date: 2020-12-08 17:23:39.612772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65ad66588403'
down_revision = '8979d20983d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('past__price__list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('booked', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('start_date')
    )
    op.add_column('price__list', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('price__list', sa.Column('is_future', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('price__list', 'is_future')
    op.drop_column('price__list', 'is_active')
    op.drop_table('past__price__list')
    # ### end Alembic commands ###
