"""empty message

Revision ID: 712384ed1e42
Revises: 6320489c2330
Create Date: 2021-01-30 14:48:27.997287

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '712384ed1e42'
down_revision = '6320489c2330'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('price__list', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('price__list', 'is_future',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('price__list', 'is_past',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('price__list', 'lock_flag',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('price__list', 'lock_flag',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('price__list', 'is_past',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('price__list', 'is_future',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('price__list', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    # ### end Alembic commands ###
