"""empty message

Revision ID: 75aec4647c30
Revises: 7aa45758776f
Create Date: 2020-12-29 16:34:50.962798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75aec4647c30'
down_revision = '7aa45758776f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('price__list_ibfk_1', 'price__list', type_='foreignkey')
    op.create_foreign_key(None, 'price__list', 'booking', ['booking_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'price__list', type_='foreignkey')
    op.create_foreign_key('price__list_ibfk_1', 'price__list', 'booking', ['booking_id'], ['id'])
    # ### end Alembic commands ###
