"""empty message

Revision ID: 7aa45758776f
Revises: 2e8131157fad
Create Date: 2020-12-29 16:32:28.869476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7aa45758776f'
down_revision = '2e8131157fad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('price__list_ibfk_1', 'price__list', type_='foreignkey')
    op.create_foreign_key(None, 'price__list', 'booking', ['booking_id'], ['id'], ondelete='SET DEFAULT')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'price__list', type_='foreignkey')
    op.create_foreign_key('price__list_ibfk_1', 'price__list', 'booking', ['booking_id'], ['id'])
    # ### end Alembic commands ###
