"""empty message

Revision ID: 7b80e7ee3f88
Revises: a0ce1f5a0a58
Create Date: 2021-07-12 16:51:10.822365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b80e7ee3f88'
down_revision = 'a0ce1f5a0a58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delete__booking', sa.Column('booking_type', sa.Enum('STANDARD', 'OWNER', 'EXTERNAL', name='booking_type'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('delete__booking', 'booking_type')
    # ### end Alembic commands ###
