"""empty message

Revision ID: 7cefda71d085
Revises: 42f19be5b389
Create Date: 2020-12-26 15:51:17.769273

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7cefda71d085'
down_revision = '42f19be5b389'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('past__booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('adults', sa.Integer(), nullable=True),
    sa.Column('children', sa.Integer(), nullable=True),
    sa.Column('infants', sa.Integer(), nullable=True),
    sa.Column('dogs', sa.Integer(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('date')
    op.add_column('booking', sa.Column('arrival_date', sa.Date(), nullable=True))
    op.add_column('booking', sa.Column('departure_date', sa.Date(), nullable=True))
    op.drop_column('future__price__list', 'booked')
    op.add_column('past__price__list', sa.Column('booking_id', sa.Integer(), nullable=True))
    op.add_column('past__price__list', sa.Column('price_2_weeks', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('past__price__list', sa.Column('price_3_weeks', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('past__price__list', sa.Column('price_4_weeks', sa.Numeric(precision=10, scale=2), nullable=True))
    op.create_foreign_key(None, 'past__price__list', 'booking', ['booking_id'], ['id'])
    op.add_column('price__list', sa.Column('booking_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'price__list', 'booking', ['booking_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'price__list', type_='foreignkey')
    op.drop_column('price__list', 'booking_id')
    op.drop_constraint(None, 'past__price__list', type_='foreignkey')
    op.drop_column('past__price__list', 'price_4_weeks')
    op.drop_column('past__price__list', 'price_3_weeks')
    op.drop_column('past__price__list', 'price_2_weeks')
    op.drop_column('past__price__list', 'booking_id')
    op.add_column('future__price__list', sa.Column('booked', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('booking', 'departure_date')
    op.drop_column('booking', 'arrival_date')
    op.create_table('date',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('booking_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date', mysql.VARCHAR(collation='utf8_bin', length=15), nullable=True),
    sa.Column('is_arrival', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('is_departure', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('is_changeover', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.CheckConstraint('(`is_arrival` in (0,1))', name='date_chk_1'),
    sa.CheckConstraint('(`is_changeover` in (0,1))', name='date_chk_3'),
    sa.CheckConstraint('(`is_departure` in (0,1))', name='date_chk_2'),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], name='date_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_bin',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('past__booking')
    # ### end Alembic commands ###
