"""removed progressive_payments from app.models

Revision ID: 81fc4e16ce9b
Revises: 19a82454ac17
Create Date: 2021-05-09 14:16:12.123954

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '81fc4e16ce9b'
down_revision = '19a82454ac17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('progressive__payment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('progressive__payment',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('price_list_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('due_by', sa.DATE(), nullable=True),
    sa.Column('amount_due', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('first_payment', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('stay_length_type', mysql.ENUM('1_WEEK', '2_WEEKS', '3_WEEKS', '4_WEEKS', collation='utf8_bin'), nullable=False),
    sa.CheckConstraint('(`first_payment` in (0,1))', name='progressive__payment_chk_1'),
    sa.ForeignKeyConstraint(['price_list_id'], ['price__list.id'], name='progressive__payment_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_bin',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
