"""empty message

Revision ID: 854976bd0483
Revises: 85f7a1260c26
Create Date: 2021-05-01 20:04:43.758087

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '854976bd0483'
down_revision = '85f7a1260c26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('delete__price__list', 'no_discount_price_4_weeks')
    op.drop_column('delete__price__list', 'no_discount_price_2_weeks')
    op.drop_column('delete__price__list', 'no_discount_price_3_weeks')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delete__price__list', sa.Column('no_discount_price_3_weeks', mysql.DECIMAL(precision=10, scale=2), nullable=True))
    op.add_column('delete__price__list', sa.Column('no_discount_price_2_weeks', mysql.DECIMAL(precision=10, scale=2), nullable=True))
    op.add_column('delete__price__list', sa.Column('no_discount_price_4_weeks', mysql.DECIMAL(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###
