"""added no_discount price fields to Price_List model

Revision ID: 85d8798f5346
Revises: 086ea46b6e0f
Create Date: 2021-04-30 13:38:17.824565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85d8798f5346'
down_revision = '086ea46b6e0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price__list', sa.Column('no_discount_price_2_weeks', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('price__list', sa.Column('no_discount_price_3_weeks', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('price__list', sa.Column('no_discount_price_4_weeks', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('price__list', 'no_discount_price_4_weeks')
    op.drop_column('price__list', 'no_discount_price_3_weeks')
    op.drop_column('price__list', 'no_discount_price_2_weeks')
    # ### end Alembic commands ###
