"""removed end-date in Price_List, added booked

Revision ID: 8979d20983d0
Revises: ce800333dbce
Create Date: 2020-12-08 12:30:25.926354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8979d20983d0'
down_revision = 'ce800333dbce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.add_column('price__list', sa.Column('booked', sa.Boolean(), nullable=True))
    op.drop_index('end_date', table_name='price__list')
    op.drop_column('price__list', 'end_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price__list', sa.Column('end_date', sa.DATE(), nullable=True))
    op.create_index('end_date', 'price__list', ['end_date'], unique=True)
    op.drop_column('price__list', 'booked')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
