"""empty message

Revision ID: 89ee6f2c256b
Revises: a386bf918449
Create Date: 2020-12-15 21:29:41.295881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89ee6f2c256b'
down_revision = 'a386bf918449'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('future__price__list', sa.Column('booked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('future__price__list', 'booked')
    # ### end Alembic commands ###
