"""added Booking.booking_type field

Revision ID: 89fa0a6d3309
Revises: b25a47a70ece
Create Date: 2021-07-07 17:35:11.437936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89fa0a6d3309'
down_revision = 'b25a47a70ece'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('booking_type', sa.Enum('standard', 'owner', 'external', name='booking_type'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking', 'booking_type')
    # ### end Alembic commands ###
