"""empty message

Revision ID: 8a8b0872077a
Revises: 7cefda71d085
Create Date: 2020-12-26 15:58:49.524665

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8a8b0872077a'
down_revision = '7cefda71d085'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('start_date', table_name='past__price__list')
    op.drop_table('past__price__list')
    op.drop_table('past__booking')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('past__booking',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('customer_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('adults', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('children', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('infants', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dogs', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('price', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name='past__booking_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_bin',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('past__price__list',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('start_date', sa.DATE(), nullable=True),
    sa.Column('price', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('booked', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('booking_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('price_2_weeks', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('price_3_weeks', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('price_4_weeks', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.CheckConstraint('(`booked` in (0,1))', name='past__price__list_chk_1'),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], name='past__price__list_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_bin',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('start_date', 'past__price__list', ['start_date'], unique=True)
    # ### end Alembic commands ###
