"""updated Delete_Price_List model

Revision ID: 8b1051d3f978
Revises: 6aa9141a1c00
Create Date: 2021-05-03 19:52:48.541686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b1051d3f978'
down_revision = '6aa9141a1c00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delete__price__list', sa.Column('discount_amount_2_weeks', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('delete__price__list', sa.Column('discount_amount_3_weeks', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('delete__price__list', sa.Column('discount_amount_4_weeks', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('delete__price__list', 'discount_amount_4_weeks')
    op.drop_column('delete__price__list', 'discount_amount_3_weeks')
    op.drop_column('delete__price__list', 'discount_amount_2_weeks')
    # ### end Alembic commands ###
