"""empty message

Revision ID: a0ce1f5a0a58
Revises: 3415df34a648
Create Date: 2021-07-12 16:46:10.861114

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a0ce1f5a0a58'
down_revision = '3415df34a648'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('delete__booking', 'booking_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delete__booking', sa.Column('booking_type', mysql.ENUM('STANDARD', 'OWNER', 'EXTERNAL', collation='utf8_bin'), nullable=True))
    # ### end Alembic commands ###
