"""added columns to Delete_Billing to match Billing

Revision ID: a103e3516125
Revises: 660eeb0a29d5
Create Date: 2021-05-30 17:28:56.432315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a103e3516125'
down_revision = '660eeb0a29d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delete__billing', sa.Column('first_invoice', sa.Boolean(), nullable=True))
    op.add_column('delete__billing', sa.Column('last_reminder', sa.Date(), nullable=True))
    op.add_column('delete__billing', sa.Column('percentage_due', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('delete__billing', 'percentage_due')
    op.drop_column('delete__billing', 'last_reminder')
    op.drop_column('delete__billing', 'first_invoice')
    # ### end Alembic commands ###
