"""billing fix part 1 of 2

Revision ID: a258d5d22041
Revises: 37eadc7e4abc
Create Date: 2021-07-15 22:41:23.615807

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a258d5d22041'
down_revision = '37eadc7e4abc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('billing', 'invoice_status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('billing', sa.Column('invoice_status', mysql.ENUM('DRAFT', 'ACCEPTED', 'ACTIVE', 'OVERDUE', 'PAID', 'INACTIVE', collation='utf8_bin'), nullable=True))
    # ### end Alembic commands ###
