"""empty message

Revision ID: afc5be7fea2d
Revises: 3fdc3ebbf907
Create Date: 2021-05-22 10:15:44.446178

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'afc5be7fea2d'
down_revision = '3fdc3ebbf907'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('billing', 'note')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('billing', sa.Column('note', mysql.VARCHAR(collation='utf8_bin', length=30), nullable=True))
    # ### end Alembic commands ###
