"""empty message

Revision ID: b015964d17bc
Revises: c00652fae690
Create Date: 2020-09-28 17:32:46.021703

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b015964d17bc'
down_revision = 'c00652fae690'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('address_line_1', sa.String(length=30), nullable=True))
    op.add_column('customer', sa.Column('address_line_2', sa.String(length=30), nullable=True))
    op.add_column('customer', sa.Column('county_or_region', sa.String(length=30), nullable=True))
    op.add_column('customer', sa.Column('first_name', sa.String(length=30), nullable=True))
    op.add_column('customer', sa.Column('last_name', sa.String(length=30), nullable=True))
    op.add_column('customer', sa.Column('postcode', sa.String(length=30), nullable=True))
    op.add_column('customer', sa.Column('town_or_city', sa.String(length=30), nullable=True))
    op.drop_column('customer', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('name', mysql.VARCHAR(collation='utf8_bin', length=30), nullable=True))
    op.drop_column('customer', 'town_or_city')
    op.drop_column('customer', 'postcode')
    op.drop_column('customer', 'last_name')
    op.drop_column('customer', 'first_name')
    op.drop_column('customer', 'county_or_region')
    op.drop_column('customer', 'address_line_2')
    op.drop_column('customer', 'address_line_1')
    # ### end Alembic commands ###
