"""empty message

Revision ID: b13f8c6a5b07
Revises: 9bc7f3cd7975
Create Date: 2020-12-12 11:53:04.165513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b13f8c6a5b07'
down_revision = '9bc7f3cd7975'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price__list', sa.Column('price_2_week', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('price__list', sa.Column('price_3_week', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('price__list', sa.Column('price_4_week', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('price__list', 'price_4_week')
    op.drop_column('price__list', 'price_3_week')
    op.drop_column('price__list', 'price_2_week')
    # ### end Alembic commands ###
