"""empty message

Revision ID: b1fdae220ad8
Revises: 03df81035884
Create Date: 2021-03-21 11:22:29.289256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1fdae220ad8'
down_revision = '03df81035884'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking', 'total_due_by')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('total_due_by', sa.DATE(), nullable=True))
    # ### end Alembic commands ###
