"""changed Price_List.blocked to Price_List.block_flag

Revision ID: b25a47a70ece
Revises: 2eb93092e9eb
Create Date: 2021-06-19 14:51:45.986264

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b25a47a70ece'
down_revision = '2eb93092e9eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price__list', sa.Column('block_flag', sa.Boolean(), nullable=True))
    op.drop_column('price__list', 'blocked')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price__list', sa.Column('blocked', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('price__list', 'block_flag')
    # ### end Alembic commands ###
