"""empty message

Revision ID: b7bdf0421bd1
Revises: b015964d17bc
Create Date: 2020-10-03 19:15:22.544157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7bdf0421bd1'
down_revision = 'b015964d17bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('date', sa.Column('is_arrival', sa.Boolean(), nullable=True))
    op.add_column('date', sa.Column('is_departure', sa.Boolean(), nullable=True))
    op.drop_index('date', table_name='date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('date', 'date', ['date'], unique=True)
    op.drop_column('date', 'is_departure')
    op.drop_column('date', 'is_arrival')
    # ### end Alembic commands ###
