"""Progressive_Payments converted from table to model

Revision ID: bcf1ac4a81a9
Revises: a2bbd22e915a
Create Date: 2021-05-09 11:46:17.692138

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bcf1ac4a81a9'
down_revision = 'a2bbd22e915a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('progressive__payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price_list_id', sa.Integer(), nullable=True),
    sa.Column('due_by', sa.Date(), nullable=True),
    sa.Column('amount_due', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('first_payment', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['price_list_id'], ['price__list.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('progressive_payments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('progressive_payments',
    sa.Column('price_list_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('due_by', sa.DATE(), nullable=True),
    sa.Column('amount_due', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('first_payment', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.CheckConstraint('(`first_payment` in (0,1))', name='progressive_payments_chk_1'),
    sa.ForeignKeyConstraint(['price_list_id'], ['price__list.id'], name='progressive_payments_ibfk_1'),
    mysql_collate='utf8_bin',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('progressive__payment')
    # ### end Alembic commands ###
