"""added delete tables

Revision ID: c62d1bcbf8e7
Revises: d9dcb8d39775
Create Date: 2021-01-06 17:09:38.854106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c62d1bcbf8e7'
down_revision = 'd9dcb8d39775'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delete__customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=True),
    sa.Column('last_name', sa.String(length=30), nullable=True),
    sa.Column('email_address', sa.String(length=30), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('address_line_1', sa.String(length=30), nullable=True),
    sa.Column('address_line_2', sa.String(length=30), nullable=True),
    sa.Column('town_or_city', sa.String(length=30), nullable=True),
    sa.Column('county_or_region', sa.String(length=30), nullable=True),
    sa.Column('postcode', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('delete__booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('arrival_date', sa.Date(), nullable=True),
    sa.Column('departure_date', sa.Date(), nullable=True),
    sa.Column('adults', sa.Integer(), nullable=True),
    sa.Column('children', sa.Integer(), nullable=True),
    sa.Column('infants', sa.Integer(), nullable=True),
    sa.Column('dogs', sa.Integer(), nullable=True),
    sa.Column('stay_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('dog_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('delete__price__list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_2_weeks', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_3_weeks', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_4_weeks', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('is_past', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_future', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('start_date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('delete__price__list')
    op.drop_table('delete__booking')
    op.drop_table('delete__customer')
    # ### end Alembic commands ###
