"""empty message

Revision ID: ce800333dbce
Revises: b7bdf0421bd1
Create Date: 2020-10-04 11:25:31.186733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce800333dbce'
down_revision = 'b7bdf0421bd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('date', sa.Column('is_changeover', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('date', 'is_changeover')
    # ### end Alembic commands ###
