"""empty message

Revision ID: d21d6dec7b63
Revises: b1fdae220ad8
Create Date: 2021-03-21 11:22:48.093538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd21d6dec7b63'
down_revision = 'b1fdae220ad8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('total_due_by', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking', 'total_due_by')
    # ### end Alembic commands ###
