"""addedPrice_List.discount_amount_[2-4]_weeks

Revision ID: d4c334a5f179
Revises: 854976bd0483
Create Date: 2021-05-03 14:42:35.497765

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd4c334a5f179'
down_revision = '854976bd0483'
branch_labels = None
depends_on = None


def upgrade():
    # ### end Alembic commands ###
	return

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
	return
    # ### end Alembic commands ###
