"""addedPrice_List.discount_amount_[2-4]_weeks

Revision ID: d4c334a5f179
Revises: 854976bd0483
Create Date: 2021-05-03 14:42:35.497765

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd4c334a5f179'
down_revision = '854976bd0483'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_2_weeks', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_3_weeks', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_4_weeks', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('discount_amount_2_weeks', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('discount_amount_3_weeks', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('discount_amount_4_weeks', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('range_type', sa.Enum('PAST', 'ACTIVE', 'FUTURE', name='range_type'), nullable=True),
    sa.Column('lock_flag', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('start_date')
    )
    op.drop_index('start_date', table_name='price__list')
    op.drop_table('price__list')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price__list',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('start_date', sa.DATE(), nullable=True),
    sa.Column('price', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('price_2_weeks', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('price_3_weeks', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('price_4_weeks', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('booking_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lock_flag', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('range_type', mysql.ENUM('PAST', 'ACTIVE', 'FUTURE', collation='utf8_bin'), nullable=True),
    sa.CheckConstraint('(`lock_flag` in (0,1))', name='price__list_chk_4'),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], name='price__list_ibfk_1', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_bin',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('start_date', 'price__list', ['start_date'], unique=True)
    op.drop_table('price_list')
    # ### end Alembic commands ###
