"""deleted Past_Price_List and Future_Price_List and combined into single table Price_List

Revision ID: d9dcb8d39775
Revises: 036f54c7b5d0
Create Date: 2021-01-03 17:32:36.718499

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd9dcb8d39775'
down_revision = '036f54c7b5d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('start_date', table_name='future__price__list')
    op.drop_table('future__price__list')
    op.drop_index('start_date', table_name='past__price__list')
    op.drop_table('past__price__list')
    op.add_column('price__list', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('price__list', sa.Column('is_future', sa.Boolean(), nullable=True))
    op.add_column('price__list', sa.Column('is_past', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('price__list', 'is_past')
    op.drop_column('price__list', 'is_future')
    op.drop_column('price__list', 'is_active')
    op.create_table('past__price__list',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('start_date', sa.DATE(), nullable=True),
    sa.Column('price', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('price_2_weeks', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('price_3_weeks', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('price_4_weeks', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('booking_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], name='past__price__list_ibfk_1', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_bin',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('start_date', 'past__price__list', ['start_date'], unique=True)
    op.create_table('future__price__list',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('start_date', sa.DATE(), nullable=True),
    sa.Column('price', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('price_2_weeks', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('price_3_weeks', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('price_4_weeks', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('booking_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], name='future__price__list_ibfk_1', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_bin',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('start_date', 'future__price__list', ['start_date'], unique=True)
    # ### end Alembic commands ###
