"""empty message

Revision ID: de27edcdef73
Revises: 167d7efb603b
Create Date: 2021-04-12 17:01:36.395537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de27edcdef73'
down_revision = '167d7efb603b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('billing_ibfk_2', 'billing', type_='foreignkey')
    op.create_foreign_key(None, 'billing', 'billing', ['linked_invoice'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'billing', type_='foreignkey')
    op.create_foreign_key('billing_ibfk_2', 'billing', 'billing', ['linked_invoice'], ['invoice_reference'])
    # ### end Alembic commands ###
