"""added Billing.first_invoice flag

Revision ID: e96232c548c4
Revises: 6c0b3162e29a
Create Date: 2021-05-24 13:14:08.996886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e96232c548c4'
down_revision = '6c0b3162e29a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('billing', sa.Column('first_invoice', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('billing', 'first_invoice')
    # ### end Alembic commands ###
