"""changed Delete_Billing.booking_id to integer, not foreign key

Revision ID: e9af5b972803
Revises: a103e3516125
Create Date: 2021-05-30 17:30:06.568100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9af5b972803'
down_revision = 'a103e3516125'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('delete__billing_ibfk_1', 'delete__billing', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('delete__billing_ibfk_1', 'delete__billing', 'booking', ['booking_id'], ['id'])
    # ### end Alembic commands ###
