"""empty message

Revision ID: ed4a0f48eebc
Revises: 48a87858fa89
Create Date: 2021-04-03 17:43:06.814856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed4a0f48eebc'
down_revision = '48a87858fa89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'cancellation__breakpoint', ['cancel_by'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cancellation__breakpoint', type_='unique')
    # ### end Alembic commands ###
