"""empty message

Revision ID: f192a22175c8
Revises: e5ad19658758
Create Date: 2020-12-13 12:51:43.697425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f192a22175c8'
down_revision = 'e5ad19658758'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('price__list__settings', 'active_prices_range')
    op.drop_column('price__list__settings', 'future_prices_range')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price__list__settings', sa.Column('future_prices_range', sa.DATE(), nullable=True))
    op.add_column('price__list__settings', sa.Column('active_prices_range', sa.DATE(), nullable=True))
    # ### end Alembic commands ###
