"""added max_segment_length to Price_List_Settings

Revision ID: f731af2d82b1
Revises: 89ee6f2c256b
Create Date: 2020-12-17 18:49:39.798588

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f731af2d82b1'
down_revision = '89ee6f2c256b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price__list__settings', sa.Column('max_segment_lengh', sa.Integer(), nullable=True))
    op.drop_column('price__list__settings', 'active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price__list__settings', sa.Column('active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('price__list__settings', 'max_segment_lengh')
    # ### end Alembic commands ###
