"""added first_payment boolean to Payment_Breakpoint model

Revision ID: f8e272ff1959
Revises: 06fa25c57cc6
Create Date: 2021-03-28 11:59:19.223896

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f8e272ff1959'
down_revision = '06fa25c57cc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment__breakpoint', sa.Column('first_payment', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'payment__breakpoint', ['due_by'])
    op.drop_column('payment__breakpoint', 'is_percentage')
    op.drop_column('payment__breakpoint', 'due_on_receipt')
    op.drop_column('payment__breakpoint', 'is_absolute')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment__breakpoint', sa.Column('is_absolute', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('payment__breakpoint', sa.Column('due_on_receipt', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('payment__breakpoint', sa.Column('is_percentage', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'payment__breakpoint', type_='unique')
    op.drop_column('payment__breakpoint', 'first_payment')
    # ### end Alembic commands ###
